### ISSUE TITLE
Hamburger menu doesn't open in Firefox

### ISSUE THREAD

**Issue by ahmedashfaq027** [ahmedashfaq027/portfolio#2]
Hamburger menu can be seen when the browser width is at least 925px. When clicked on it, the Navbar links (Positioned absolute) should be displayed.  This doesn't work on Firefox.

**Comment by avsjukad** [comment]
hello, can I work on this issue?

**Comment by ahmedashfaq027** [comment]
> hello, can I work on this issue?

Yes, please. Go Ahead!
